### ISSUE TITLE
Importing time entries (from toggle) without any assigned project results in error

### ISSUE THREAD

**Issue by dahaupt** [mikerourke/transfermyti.me#18]
I was trying to import my full workspace from Toggl to an existing workspace in Clockify.

Replacing the last line into 
```typescript
projectId: R.isNil(timeEntry.pid) ? null : timeEntry.pid.toString(),
```
could solve the issue, but as I'm not familiar with the project and TypeScript I have not created a PR yet.

**Stacktrace**:
```
appActions.ts:36 TypeError: Cannot read property 'toString' of null
    at transformFromResponse (togglTimeEntriesSagas.ts:289)
    at togglTimeEntriesSagas.ts:195
    at Array.map (<anonymous>)
    at togglTimeEntriesSagas.ts:188
    at step (togglTimeEntriesSagas.ts:17)
    at Object.next (togglTimeEntriesSagas.ts:17)
    at next (redux-saga-core.esm.js:1157)
    at currCb (redux-saga-core.esm.js:1251)
```

**Comment by mikerourke** [comment]
@dahaupt I deployed a fix for this earlier today. Could you try it again and let me know if it’s working now?

**Comment by dahaupt** [comment]
@mikerourke I just tested the import again. Seems to work fine now. Thanks a lot for your fast fix!
