### ISSUE TITLE
Stuck at final step after pressing start - nothing happens

### ISSUE THREAD

**Issue by Ljuk67** [mikerourke/transfermyti.me#22]
Hi Mike, great work on this workflow / tool!

I entered the API keys, my data was pulled and shown, I left everyting ticked (included), proceeded to the last step, pressed START and nothing happens for over 20minutes now. the numbers don't change, the start button is blanked out, see https://prnt.sc/qr7u0a

I'm running it on the latest Chrome, the console shows no errors, except an (I guesss unrelated) warning for the Grammarly extension:

Grammarly.js:2 [DEFAULT]: WARN : Using DEFAULT root logger
t.printToConsole @ Grammarly.js:2

Any hints?

thanks,
Lukas

**Comment by mikerourke** [comment]
@Ljuk67 I was having this issue yesterday as well. I tried making some requests to the Clockify API using a different tool and it was taking forever. I tried it again about an hour later and it worked. Maybe their servers are getting overloaded. 

Could you try just transferring everything but your time entries first? If that works, you may have to use the transfer tool a couple of times (depending on how many time entries you have). The tool should prevent duplicate entries, so it’ll go reasonably quick.

**Comment by Ljuk67** [comment]
Hi Mike, hello Golden Girls! :D 

that worked, but after the transfer complete message, I see no toggl tags or clients in clockify? Or any other data I selected to transfer.

I tried twice to be sure, same thing both times. second time, I selected a couple of time entries too. 

Strangely, the transfer complete message was shown straight away, no delay / processing whatsoever?

**Comment by mikerourke** [comment]
Noooo!!! Someone else is having the same issue. Just out of curiosity, are you in France? I’m trying to pin down the cause and I’m beginning to suspect it’s related to internationalization.

**Comment by Ljuk67** [comment]
nope, Slovakia.

**Comment by mikerourke** [comment]
Cool, so it might be an oceanic divide thing. I’m working on fixing the issue now. I’m confident the same thing is happening on #19. I’ll let you know when I find put what’s going on. I’m heading to work now so it may be a few hours until I get back to you. I apologize for the delay (and the issues).

**Comment by Ljuk67** [comment]
cool, no worries, this isn't urgent and you're doing us a big favour, so how ever it suits you ;)

**Comment by mikerourke** [comment]
@Ljuk67 I think I found your issue. It's being caused by the workspace names not matching. So if you have only 1 Toggl workspace named "Toggl Workspace", and 1 Clockify workspace named "Clockify Workspace", the transfer would never take place because it couldn't find a target workspace to transfer data into.

I fixed the code to create a Clockify workspace if it doesn't exist, but if you want to finish the transfer *without creating a new Workspace*, you just need to update the Clockify workspace name to match the Toggl one exactly (you can always change it after you're done).

Give it a shot and let me know if it works!

**Comment by Ljuk67** [comment]
Worked like a treat! Thanks for digging in and finding the real issue, good snooping!
I did it first without time entries, now running time entries, still in progress. 

A separate workspace is ok, I want to have it all in one place, the archive is fine in a separate workspace.

The way toggl and clockify generate the workspaces is different (toggl used my email address  (before the @) and clockify used my name - separate words with capital letters. This seems hard to reconcile systematically, as people can use various versions of their names for one and the other service. Maybe a prompt before the import starts with your note "rename clockify workspace to match toggl's, you can then rename it back".

Hmmm, now time entry import is finished, it looks like it was cut off too early (only entries until mid 2017 are there. Will try to rerun. Mentioning it here in case it will help you identify a timeout you don't know about.

Anyway, great job & nice seamless and easy UI!
Thanks again
Lukas

**Comment by mikerourke** [comment]
Good to hear! There's an open issue that got opened a while ago (#5) that may be causing the date cut off error. I'll try to add some newer time entries to my test instance and see if I can reproduce it. I'm going to create a new issue so I can track it on a separate branch.

**Comment by Ljuk67** [comment]
Closing this - original issue was fixed, as per https://github.com/mikerourke/transfermyti.me/issues/22#issuecomment-577288674
