### ISSUE TITLE
Not all time entries getting transferred

### ISSUE THREAD

**Issue by mikerourke** [mikerourke/transfermyti.me#24]
## Reported By

@Ljuk67

## Current Behavior

When attempting to transfer entries from **Toggl** to **Clockify**, not all of the time entries are being transferred. Cross referenced from #22:

> Hmmm, now time entry import is finished, it looks like it was cut off too early (only entries until mid 2017 are there. Will try to rerun. Mentioning it here in case it will help you identify a timeout you don't know about.

## Expected Behavior

All time entries should be transferred to Clockify.

## Possible Causes

- API rate limiting
- Date calculations in transfer
- Because it's 2020!?

**Comment by Ljuk67** [comment]
I tried running the import again - 1800 time entries were found that weren't yet in the target workspace (clockify). When I imported, an error in a black pop up in the top right corner flashed several times and distorted the screen, but I couldn't read it (too fast). Something with API...

but the import continued to run, reached maybe 2% and flipped to transfer complete page. 

There was at least 10 min pause between the first and this import. 

Hope this helps narrow it down!
Lukas

**Comment by Ljuk67** [comment]
the cut off was at May 2017 for me, incomplete month.

**Comment by mikerourke** [comment]
Thanks! Yeah, I added an arbitrary backoff time that retries a request if it sends back a 429 error (rate limit hit). I'll try bumping that up and seeing if that fixes it. This is purely speculation, but I wonder if Clockify's servers aren't set up to handle this much continuous traffic. The backoff time is a one line of code change. Let me update and re-deploy. Try running the transfer again in about 15 minutes.

**Comment by mikerourke** [comment]
@Ljuk67 FYI, I just pushed a bug fix for an issue I found in the transform method for time entries. It's hard to say if it was causing an error. The deploy finished about 10 minutes ago, so if you tried transferring before that, it may still be failing.

**Comment by Ljuk67** [comment]
tried again just now, it failed at about 40/1800, showing this error message:
The following error occurred: Error code 400 when fetching from Clockify API.

**Comment by Ljuk67** [comment]
I'm off for today, can continue testing tomorrow...

**Comment by mikerourke** [comment]
Sounds good. It looks like there are several possible reasons for getting a `400`. I'll try to add checks for all of them and let you know when it's ready. I appreciate your patience, have a good night!

**Comment by mikerourke** [comment]
Hey @Ljuk67, just out of curiousity, are you trying to transfer time entries that are associated with a client, tag, or project that you're **not** transferring? I'm wondering if the issue is caused by trying to associate a time entry with an invalid ID.

**Comment by petero-dk** [comment]
I had the same issue, and I noticed that the transfer was halted just before an entry that had no task and no project: 

```
12/23/2015, 9:11 AM | 12/23/2015, 12:00 PM | None | None
-- | -- | -- | --
```

Going into toggl and setting a project on this task made the whole thing complete without problems.

**Comment by mikerourke** [comment]
@petero-dk Thanks for letting me know! That should be a simple fix. I can finally close this issue!

**Comment by mikerourke** [comment]
Made some minor changes to the new Clockify time entry creation method. I was able to successfully transfer time entries with no project and task from Toggl to Clockify.

**Comment by FlatBlack722** [comment]
Hi Mike. First of all, thank you for your effort in creating this tool. Unfortunately, I ran across a problem when I tried to transfer Toggl entries to Clockify. When the transfer starts, it gives me the following error: "Error code 403 when fetching from Clockify API."

In some cases I also get this one as well: "The following error occurred: Error code 400 when fetching from Clockify API. Status: Bad Request"

Do you perhaps have any recommendations on how to fix this?

**Comment by mikerourke** [comment]
Hi @FlattBlack722, did you create a new Clockify account prior to starting the transfer, or did you already have an existing account with data?

**Comment by FlatBlack722** [comment]
It's a brand new account. Initially I had some data in it and the transfer
failed. After that I used your tool to delete all entries and then tried
again to transfer enevrything to clockify. Do I also need to delete my
space before doing the transfer, or?

**Comment by mikerourke** [comment]
You shouldn’t need to. I have run into this issue before, but it’s because I deleted a workspace on Clockify through the API, but it’s still hanging around in their database for some reason. Could you try creating a new workspace in Clockify and transferring to it?

**Comment by FlatBlack722** [comment]
I will give it a try and let you know. Usually it transfers all the
projects and clients and when it starts copying time entries it copies 50
of them and then it gives an error and says that it's successfully done.
But I will give this a try what you recommend. Thanks Mike 👍

**Comment by mikerourke** [comment]
No problem! The time entry transfer issue may be due to a time entry not being associated with a project or task. If you only have a few time entries not associated with projects, I’d recommend associating them with a project for the transfer. I thought I fixed that issue but apparently it might still be causing an issue.

**Comment by FlatBlack722** [comment]
Hi Mike! So I did make some progress. I was able to transfer all of my time
entries to the work space but I had to revert that space to it's original
state (meaning setting everything back to default values eg. currency used,
project creation permissions etc.).

So now I am trying to transfer the time entries of my colleagues and when.
try to do that I get the API 403 error. Is that the error where you
indicated that each time entry from Toggl has to have a project associated
to it?
I asked my team to check their Toggl entries so I will know if that might
be the problem or not.

Thank you so far for your help! I will keep you posted.

**Comment by mikerourke** [comment]
Hi @FlattBlack722, so the tool doesn't support transfers for multiple users. Were you using your colleague's API key when you tried making the transfer, or are you trying to transfer their time entries as an administrator (with your API key)?

**Comment by FlatBlack722** [comment]
Hi Mike.

Unfortunately I was not able to resolve the problem because indeed I was
trying to transfer entries from multiple accounts. Transferring one account
works, but as soon as I try to transfer another one it does not take into
account projects in the transfer.

Therefore we decided to start from a blank sheet.

Still, your help is much appreciated! Thank you once more :)
