### ISSUE TITLE
When transferring data from Toggl to Clockify entries made by others are added as if I entered them.

### ISSUE THREAD

**Issue by greghessiu** [mikerourke/transfermyti.me#30]
I am an admin on the Toggl workspace.  When trying to use the transfer tool it includes entries others on the team made, and when the entries are added to Clockify it is as if I made the entry, not the other person.

I was originally planning to run the tool several times, once per team member to copy the information in.  Is there a way I can only transfer my time entries?

**Comment by mikerourke** [comment]
Hey @greghessiu, so I did not even think to accommodate for the scenario you are describing. I apologize for fumbling the ball on that one. I’ll update the code to ensure the entries only associated with your user ID are displayed/transferred. It should only take an hour to fix the code but I’m out of town until Sunday. I’ll take care of it Sunday night and ping you when it’s fixed. Sorry for the delay.

**Comment by mikerourke** [comment]
@greghessiu You should be good to go now. Your best bet would be to delete all of the time entries from Clockify using the tool and trying the transfer again. Let me know if you have any issues, thanks!

**Comment by greghessiu** [comment]
Thank you!
