### ISSUE TITLE
An error occurred when making a request to the API

### ISSUE THREAD

**Issue by ghost** [mikerourke/transfermyti.me#4]
Hi Mike! 

I'm just testing your tool because we want to switch from toggl to clockify. Great Work!

But I have problems to fetch projects, tasks and time entries. While the fetching process is running the error message "An error occurred when making a request to the API" pops up and the tool just finds tags and clients.

Is this a bug or do I have made something wrong?

![toggl-clockify](https://user-images.githubusercontent.com/7394403/55866340-721dae00-5b80-11e9-912a-312527ed1cf5.PNG)

**Comment by mikerourke** [comment]
I suspect it may have to do with it being a mutli-user environment. I’m finishing up the time entry transfer stuff tomorrow (it’s not working right now), then pushing it up to Netlify or Surge so I can have a few interested parties test it. It may not be ready for multi-user out of the gate, but it’s a very high priority, so I’m going to work on it right away while having people test out the single user transfer. I’ll ping you when it’s ready for testing.

**Comment by ghost** [comment]
That sounds great! 
Thank you

**Comment by mikerourke** [comment]
Hey @niggoledde, just an FYI, I got a little swamped with work today so I didn’t get as much time as I needed to finish up the time entry stuff, but I’ve got most of Sunday to knock it out. I can send you the link to the tool when it’s ready if you wanted to try transferring just your entries.

**Comment by ghost** [comment]
Hi Mike! Thanks for the update!
Please send me the link I would be happy to test your tool and give feedback!

**Comment by hernanpuente** [comment]
I can help with testing as well! I need to move 5 years of time entries from Toggl to Clockify :)

**Comment by mikerourke** [comment]
Closing this because I haven't encountered this bug with the newly refactored version. If the problem crops up again, I can create a new issue.
