### ISSUE TITLE
[Bug] Years are not correctly detected

### ISSUE THREAD

**Issue by ulfgebhardt** [mikerourke/transfermyti.me#5]
Years are not correctly detected; the web interface shows only `2019` even tho there is entries from 2018.

**Comment by mikerourke** [comment]
I’ll take a look. I know that the code I wrote to check the years was prone to issues. There’s probably a much better approach.

**Comment by mikerourke** [comment]
Closing this because I haven't encountered this bug with the newly refactored version. If the problem crops up again, I can create a new issue.
