### ISSUE TITLE
[Bug] Duplicates are created when importing twice

### ISSUE THREAD

**Issue by ulfgebhardt** [mikerourke/transfermyti.me#6]
Duplicates are created when importing twice - there should be an option to crosscheck if the entry is already present - or (preferable) a tool which detects duplicates and gives the option to remove them.
-> It might be wise to add tags to transfered time entries

**Comment by mikerourke** [comment]
I started working on this but didn’t want it to hold up the initial release (which I was aiming for Monday). It’s going to require some complex logic to prevent duplicate entries. In the interim, I can add the delete functionality in pretty quickly. I already have some a script that deletes everything on Clockify (in the /scripts folder). I just need to port it over to TypeScript.

**Comment by mikerourke** [comment]
This should be done and appears to be working, so I'm closing it.
