### ISSUE TITLE
[Feature] Delete all Timeentries

### ISSUE THREAD

**Issue by ulfgebhardt** [mikerourke/transfermyti.me#7]
It would be a very helpful functionality to delete all time entries.

Consider this:
- User wants to transfer toggl -> clockify
- An Error occurs or he makes an mistake
- Broken/Wrong/Incomplete time entries are present in Clockify
- User wants to clean Clockify in oder to do the transfereprocess correctly.

**Comment by mikerourke** [comment]
See #6. I agree with adding this in, but I prefer that this tool have a limited feature set. First and foremost, it is intended to transfer data. If I start adding too many bells and whistles, it could get out of hand.

**Comment by mikerourke** [comment]
Added on #15.
