### ISSUE TITLE
Limit time entries to those associated with selected projects

### ISSUE THREAD

**Issue by amirblum** [mikerourke/transfermyti.me#76]
Hey Mike, great tool :)

This is a feature request  - I'm trying to transfer data from one Toggl workspace to multiple Clockify workspaces, by running the tool once-per-workspace and selecting the clients and projects I want for that workspace.

The issue is that there's no way to limit the tool to only transfer entries associated with the projects I am transferring.

My solution for now is to import all entries, which un-assigns the project for the entries associated with projects I haven't selected. I then intend to bulk delete all the entries that don't have a project associated with them from within Clockify (which requires a basic plan).

Would be great to either select/deselect entries by project, for either transferring or bulk-deletion from within transfermyti.me!

Thanks for your efforts 🙏

**Comment by mikerourke** [comment]
Hi @amirblum, I apologize for the delayed response. It shouldn't be too hard to add that in, and it's a great idea! I'll move this one to the top of the list. I'm a little strapped for time right now, but I should be have some bandwidth to work on it in a couple of weeks. I'll let you know when it's ready.

**Comment by amirblum** [comment]
No worries about the response - your time is highly valued and I appreciate that you would even take a feature request!

I have already imported all my entries, so currently a way to bulk-delete all time entries without an assigned project would be most helpful. That being said, I do have colleagues who are also looking to move using your tool, so I'm sure more specific selection during transfer of data would be appreciated by them.

Thanks!
